-- CreateTable
CREATE TABLE "runningInstances" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "lastHearBeat" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "runningInstances_pkey" PRIMARY KEY ("id")
);
